image: python:3.9-slim

stages:
  - lint
  - test
  - coverage
  - docs

variables:
  PYTHONPATH: "$CI_PROJECT_DIR/src"
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

cache:
  paths:
    - .cache/pip
    - .pytest_cache
    - __pycache__

.default_settings:
  before_script:
    - python --version
    - pip install --no-cache-dir -r requirements.txt
    - mkdir -p tests/reports
    - mkdir -p tests/artefacts
    - export PYTHONPATH=$CI_PROJECT_DIR/src

lint:
  stage: lint
  extends: .default_settings
  tags:
    - docker
  allow_failure: true
  script:
    - ruff check src -v    

test:
  stage: test
  extends: .default_settings
  tags:
    - docker
  allow_failure: false  
  script:
    - coverage run -m pytest -v
  artifacts:
    paths:
      - .coverage
      - tests/reports/*.html
      - tests/artefacts/
    expire_in: 1 week

coverage:
  stage: coverage
  extends: .default_settings
  tags:
    - docker
  allow_failure: true  
  script:
    - if [ -f .coverage ]; then coverage report -m; fi
    - if [ -f .coverage ]; then coverage html -d tests/reports/coverage_html; fi
  artifacts:
    paths:
      - tests/reports/coverage_html/
    expire_in: 1 week

# docs:
#   stage: docs
#   tags:
#     - docker
#   before_script:
#     - pip install --no-cache-dir mkdocs-material mkdocstrings
#   script:
#     - mkdocs build
#   artifacts:
#     paths:
#       - public/
#     expire_in: 1 week
#   rules:
#     - if: '$CI_COMMIT_BRANCH == "main"' # dokumentaatio generoidaan vain päähaaran muutoksissa