image: python:3.9-slim

stages:
  - lint
  - test
  - coverage

variables:
  PYTHONPATH: "/app/src"
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

cache:
  paths:
    - .cache/pip

.default_settings:
  before_script:
    - python --version
    - pip install --no-cache-dir -r requirements.txt
    - mkdir -p tests/reports
    - mkdir -p tests/artefacts

lint:
  stage: lint
  extends: .default_settings
  tags:
    - tests
  allow_failure: true
  script:
    - ruff check src -v    

test:
  stage: test
  extends: .default_settings
  tags:
    - tests
  allow_failure: true  
  script:
    - coverage run -m pytest -v --tb=short --html=tests/reports/unit_test_report.html --self-contained-html tests/unit_tests.py
    - coverage run -m pytest -v --tb=short --html=tests/reports/api_test_report.html --self-contained-html tests/api_tests.py
    - coverage run -m pytest -v --tb=short --html=tests/reports/integration_test_report.html --self-contained-html tests/integration_tests.py
  artifacts:
    paths:
      - .coverage
      - tests/reports/*.html
      - tests/artefacts/
    expire_in: 1 week

coverage:
  stage: coverage
  extends: .default_settings
  tags:
    - tests
  allow_failure: true  
  script:
    - coverage report -m
    - coverage html -d tests/reports/coverage_html
  artifacts:
    paths:
      - tests/reports/coverage_html/
    expire_in: 1 week
