services:
  streamlit:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8501:8501"  # Streamlit-portti
    environment:
      GITLAB_TOKEN: "${GITLAB_TOKEN}"
      PYTHONPATH: "/app/src"
    volumes:
      - ./tests/reports:/app/tests/reports
      - ./.env:/app/.env
      - ./.streamlit:/app/.streamlit
    command: >
      sh -c "
      pip install -r requirements.txt &&
      echo '***************************************************************************************************************************************************************' &&
      echo 'PALIKKAPALVELUT-SOVELLUS SAATAVILLA: http://localhost:8501' &&
      echo '***************************************************************************************************************************************************************' &&
      streamlit run src/app.py --server.port=8501 --server.enableCORS=false 
      "

  tests:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    environment:
      GITLAB_TOKEN: "${GITLAB_TOKEN}"
      CLOCKIFY_TOKEN: "${CLOCKIFY_TOKEN}"
      PYTHONPATH: "/app/src"
    volumes:
      - ./tests:/app/tests
      - ./tests/reports:/app/tests/reports
      - ./.env:/app/.env
    command: >
      sh -c "
      echo '***************************************************************************************************************************************************************' &&
      ruff check src -v &&
      echo '***************************************************************************************************************************************************************' &&
      coverage run -m pytest -v --tb=short --html=tests/reports/unit_test_report.html --self-contained-html tests/unit_tests.py &&
      echo '***************************************************************************************************************************************************************' &&
      coverage run -m pytest -v --tb=short --html=tests/reports/api_test_report.html --self-contained-html tests/api_tests.py &&
      echo '***************************************************************************************************************************************************************' &&
      coverage run -m pytest -v --tb=short --html=tests/reports/integration_test_report.html --self-contained-html tests/integration_tests.py &&
      echo '***************************************************************************************************************************************************************' &&
      coverage report -m &&
      coverage html -d tests/reports/coverage_html &&
      echo '***************************************************************************************************************************************************************' &&
      echo 'TESTIRAPORTIT SAATAVILLA: http://localhost:8010' &&
      echo '***************************************************************************************************************************************************************'
      "

  reports:
    image: python:3.9-slim
    command: >
      sh -c "
      echo '***************************************************************************************************************************************************************' &&
      echo 'YKSIKKÖTESTIRAPORTTI SAATAVILLA: http://localhost:8010/unit_test_report.html' &&
      echo 'API-TESTIRAPORTTI SAATAVILLA: http://localhost:8010/api_test_report.html' &&
      echo 'INTEGRAATIOTESTIRAPORTTI SAATAVILLA: http://localhost:8010/integration_test_report.html' &&
      echo 'TESTIEN KATTAVUUSRAPORTTI SAATAVILLA: http://localhost:8010/coverage_html/index.html' &&
      echo '***************************************************************************************************************************************************************' &&
      python3 -m http.server 8010 -d /app/tests/reports
      "
    volumes:
      - ./tests/reports:/app/tests/reports
    ports:
      - "8010:8010"  # Testiraporttien portti

  docs:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8502:8502"  # MkDocs-dokumentaation portti
    command: >
      sh -c "
      echo '***************************************************************************************************************************************************************' &&
      echo 'PROJEKTIDOKUMENTAATIO SAATAVILLA: http://localhost:8502' &&
      echo '***************************************************************************************************************************************************************' &&
      mkdocs serve -a 0.0.0.0:8502
      "

  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8088:8088"  # API:n ulkoinen portti
    environment:
      PYTHONPATH: "/app/src:/app/api"
    env_file:
      - .env
    volumes:
      - ./api:/app/api
      - ./src:/app/src
    command: >
      sh -c "
      pip install -r requirements.txt &&
      echo '***************************************************************************************************************************************************************' &&
      echo 'API-RAJAPINTA SAATAVILLA: http://localhost:8088' &&
      echo 'API-DOKUMENTAATIO SAATAVILLA: http://localhost:8088/docs' &&
      echo '***************************************************************************************************************************************************************' &&
      uvicorn api.main:app --host 0.0.0.0 --port 8088
      "