services:
  reporousku:
    image: gitlab.dclabra.fi:4567/projektiopinnot-4-digitaaliset-palvelut/palikkapalvelut/reporousku
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.palikkapalvelut.rule=Host(`jvprojekti2024s.dclabra.fi`) && PathPrefix(`/palikkapalvelut`)"
      - "traefik.http.routers.palikkapalvelut.entrypoints=web"
      - "traefik.http.routers.palikkapalvelut.middlewares=palikkapalvelut-strip-prefix"
      - "traefik.http.middlewares.palikkapalvelut-strip-prefix.stripprefix.prefixes=/palikkapalvelut"
    expose:
      - "8511"
    networks:
      - microservices-network
    command: >
      sh -c "
      streamlit run src/app.py --server.port=8511 --server.enableCORS=false 
      "
    volumes:
      - ./.streamlit:/app/.streamlit
    
networks:
  microservices-network:
    external: true