services:
  palikka:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8501:8501"
    environment:
      GITLAB_TOKEN: "${GITLAB_TOKEN}"
      PYTHONPATH: "/app/src"
    volumes:
      - ./tests/reports:/app/tests/reports
    command: >
      sh -c "
      ruff check src -v &&
      pytest -v -s --tb=short --html=tests/reports/report.html --self-contained-html tests/test_project_data.py
      "