services:
  palikka:
    build:
      context: .
      dockerfile: Dockerfile 
    ports:
      - "8501:8501"
    environment:
      GITLAB_TOKEN: "${GITLAB_TOKEN}"
      PYTHONPATH: "/app/src"

  ruff:
    build:
      context: .
      dockerfile: Dockerfile
    command: ruff check src