services:
  palikka:
    build:
      context: .
      dockerfile: Dockerfile 
    ports:
      - "8501:8501"
    environment:
      GITLAB_TOKEN: "${GITLAB_TOKEN}"
    volumes:
      - ./tests/reports:/app/tests/reports

  # Staattinen analyysi `ruff`-lintterillä
  ruff:
    image: python:3.9-slim
    working_dir: /app
    volumes:
      - .:/app
    command: ["ruff", "check", "src"]