services:
  streamlit:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8501:8501"  # Streamlit-portti
    environment:
      GITLAB_TOKEN: "${GITLAB_TOKEN}"
      PYTHONPATH: "/app/src"
    volumes:
      - ./tests/reports:/app/tests/reports
      - ./.env:/app/.env
      - ./src/.streamlit:/app/.streamlit
    command: >
      sh -c "
      pip install -r requirements.txt &&
      streamlit run src/app.py --server.port=8501 --server.enableCORS=false &&
      echo 'PalikkaPalvelut-sovellus saatavilla: http://localhost:8501' 
      "

  tests:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      GITLAB_TOKEN: "${GITLAB_TOKEN}"
      PYTHONPATH: "/app/src"
    volumes:
      - ./tests:/app/tests
      - ./tests/reports:/app/tests/reports
    command: >
      sh -c "
      ruff check src -v &&
      coverage run -m pytest -v --tb=short --html=tests/reports/unit_test_report.html --self-contained-html tests/unit_tests.py &&
      coverage run -m pytest -v --tb=short --html=tests/reports/api_test_report.html --self-contained-html tests/api_tests.py &&
      coverage run -m pytest -v --tb=short --html=tests/reports/integration_test_report.html --self-contained-html tests/integration_tests.py &&
      coverage report -m &&
      coverage html -d tests/reports/coverage_html &&
      echo 'Testiraportit saatavilla: http://localhost:8010'
      "

  reports:
    image: python:3.9-slim
    command: >
      sh -c "
      python3 -m http.server 8010 -d /app/tests/reports &&
      echo 'Yksikkötestiraportti saatavilla: http://localhost:8010/unit_test_report.html' &&
      echo 'API-testiraportti saatavilla: http://localhost:8010/api_test_report.html' &&
      echo 'Integraatiotestiraportti saatavilla: http://localhost:8010/integration_test_report.html' &&
      echo 'Kattavuusraportti saatavilla: http://localhost:8010/coverage_html/index.html'
      "
    volumes:
      - ./tests/reports:/app/tests/reports
    ports:
      - "8010:8010"  # Testiraporttien portti

  docs:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8502:8502"  # MkDocs-dokumentaation portti
    command: >
      sh -c "
      mkdocs serve -a 0.0.0.0:8502 &&
      echo 'Projektidokumentaatio saatavilla: http://localhost:8502'
      "

  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8088:8088"  # API:n ulkoinen portti
    environment:
      PYTHONPATH: "/app/src:/app/api"
    env_file:
      - .env
    volumes:
      - ./api:/app/api
      - ./src:/app/src
    command: >
      sh -c "
      pip install -r requirements.txt &&
      uvicorn api.main:app --host 0.0.0.0 --port 8088 &&
      echo 'API-rajapinta saatavilla: http://localhost:8088'
      "