services:
  streamlit:
    build:
      context: .
      dockerfile: Dockerfile
    image: gitlab.dclabra.fi:4567/projektiopinnot-4-digitaaliset-palvelut/palikkapalvelut/reporousku
    environment:
      GITLAB_TOKEN: "${GITLAB_TOKEN}"
      PYTHONPATH: "/app/src"
    volumes:
      - ./tests/reports:/app/tests/reports
      - ./.env:/app/.env
      - ./.streamlit:/app/.streamlit
    command: >
      sh -c "
      streamlit run src/app.py --server.port=8511 --server.enableCORS=false 
      "